const ROUTES = {
    DASHBOARD: "/dashboard",
    ASSET_CATEGORIES: "/dashboard/asset/category",
    ASSETS: "/dashboard/asset/manage",
    CREATE_ASSET: "/dashboard/asset/manage/create",
    EDIT_ASSET: "/dashboard/asset/manage/edit",
    ASSET_DETAIL: "/dashboard/asset/manage/detail",
    ASSET_DETAIL_PUBLIC: "/asset-detail",
    ASSET_BRAND: "/dashboard/asset/brand",
    ASSET_STORE: "/dashboard/asset/store",
    ASSET_LOCATION: "/dashboard/asset/location",
    ASSET_QR_PRINT: "/dashboard/asset/qr-print",
    EMPLOYEES: "/dashboard/manage-employee",
    CREATE_EMPLOYEE: "/dashboard/create-employee",
    UPDATE_EMPLOYEE: "/dashboard/edit-employee",
    SIGN_OUT: "/auth/signout",
    SIGN_IN: "/auth",
    MEDIA_LIBRARY: "/dashboard/media-library",
    FORBIDDEN: "/dashboard/forbidden",
    ROLES: "/dashboard/manage-role",
    ADMINS: "/dashboard/manage-admin",
    CREATE_ADMIN: "/dashboard/create-admin",
    EDIT_ADMIN: "/dashboard/edit-admin",
    SITE_OPTIONS: "/dashboard/site-options",
    FUNDING_APPLICATION: "/dashboard/pengajuan",
    CREATE_FUNDING_APPLICATION: "/pengajuan",
    PRINT_FUNDING_APPLICATION: "/pengajuan/print",
    EDIT_FUNDING_APPLICATION: "/dashboard/pengajuan/edit",
    DISTRIBUTION_PROGRAM: "/dashboard/distribution/program",
    DISTRIBUTION_ITEM: "/dashboard/distribution/item",
    DISTRIBUTION_BENEFICIARY: "/dashboard/distribution/beneficiary",
    DISTRIBUTION_APPLICATION: "/dashboard/distribution/pengajuan-quran",
    DISTRIBUTION_APPLICATION_DETAIL: "/dashboard/distribution/pengajuan-quran",
};

export default ROUTES;
