import { Inter } from "next/font/google";
import "./globals.css";
import ClientSideProvider from "@/contexts/ClientSideProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <meta name="robots" content="noindex,nofollow" />
            <body className={inter.className}>
                <ClientSideProvider>
                    {children}
                </ClientSideProvider>
            </body>
        </html>
    );
}
